name: Show last tweet

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install Package Dependencies
        env:
          GITHUB_PAT: ${{ secrets.TWEET_PAT }}
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "install.packages('devtools')"
          Rscript -e "devtools::install_github('gadenbuie/tweetrmd', ref='main')"
          Rscript -e "remotes::install_github('rstudio/webshot2', ref='main')"
          Rscript -e "install.packages('rtweet')"
      - name: Run script
        env:
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run: |-
          Rscript -e "source('script.R')"
      - name: Commit results
        run: |
          git config --global user.email "zhiyang@usc.edu"
          git config --global user.name "zhiiiyang"
          git commit -m "Update the latest tweet" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
